name: recovery_chaining
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.2
      - ale-py==0.8.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - autolab-core==1.1.1
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - black==25.1.0
      - boto3==1.36.26
      - botocore==1.36.26
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - colorful==0.5.6
      - colorlog==6.9.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - d3rlpy==2.3.0
      - dataclasses-json==0.6.7
      - decorator==5.2.0
      - dill==0.3.9
      - distlib==0.3.9
      - docker-pycreds==0.4.0
      - etils==1.12.0
      - evdev==1.9.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - farama-notifications==0.0.4
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - googleapis-common-protos==1.68.0
      - grpcio==1.70.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - h5py==3.13.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-joblib-launcher==1.2.0
      - hydra-ray-launcher==1.2.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - ipython==8.32.0
      - jax-jumpy==1.0.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - minigrid==3.0.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mujoco==3.1.6
      - multidict==6.1.0
      - multiprocess==0.70.17
      - mypy-extensions==1.0.0
      - narwhals==1.27.1
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-spy==0.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.6.1
      - pygments==2.19.1
      - pynput==1.7.8
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - pyquaternion==0.9.9
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.1
      - pyyaml==6.0.2
      - ray==2.42.1
      - referencing==0.36.2
      - requests==2.32.3
      - rich==13.9.4
      - robosuite==1.4.0
      - rpds-py==0.23.1
      - rsa==4.9
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.11.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scikit-spatial==8.1.0
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shimmy==1.3.0
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - stable-baselines3==2.2.1
      - stack-data==0.6.3
      - structlog==25.1.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tomli==2.2.1
      - torch==2.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.2.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - virtualenv==20.29.2
      - wandb==0.19.7
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xgboost==2.1.4
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/svats2/miniconda3/envs/recovery_chaining
