name: belief
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pybox2d=2.3.10=py310h122e73d_2
  - python=3.10.13=h955ad1f_0
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.24.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - ale-py==0.8.1
      - alembic==1.13.1
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.1.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - atari-py==0.2.9
      - attrs==23.1.0
      - autolab-core==1.1.1
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - black==23.10.1
      - bleach==6.1.0
      - boto3==1.15.6
      - botocore==1.18.18
      - box2d-py==2.3.5
      - cachetools==5.3.2
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - chex==0.1.85
      - chumpy==0.70
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.7.0
      - comm==0.1.4
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==41.0.5
      - cycler==0.12.1
      - cython==0.29.36
      - d3rlpy==2.3.0
      - dataclasses-json==0.6.1
      - datasets==2.19.0
      - debugpy==1.8.0
      - decorator==4.4.2
      - defusedxml==0.7.1
      - diffusers==0.21.4
      - dill==0.3.7
      - dm-control==1.0.15
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - easydict==1.11
      - einops==0.7.0
      - etils==1.7.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fairscale==0.4.4
      - farama-notifications==0.0.4
      - fasteners==0.15
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - filterpy==1.4.5
      - flatbuffers==1.12
      - fonttools==4.43.1
      - fqdn==1.5.1
      - free-mujoco-py==2.1.6
      - freetype-py==2.4.0
      - frozenlist==1.4.0
      - fsspec==2024.6.0
      - future-fstrings==1.2.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - glfw==2.7.0
      - google-auth==2.23.4
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.0.1
      - grpcio==1.59.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - h5py==3.10.0
      - huggingface-hub==0.22.2
      - huggingface-sb3==3.0
      - humanfriendly==10.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.2.0
      - hydra-joblib-launcher==1.2.0
      - hydra-ray-launcher==0.1.2
      - hydra-submitit-launcher==1.2.0
      - hydra-wandb-sweeper==0.0.1
      - idna==3.4
      - imageio==2.31.6
      - imageio-ffmpeg==0.4.9
      - imitation==1.0.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - ipykernel==6.26.0
      - ipython==8.17.1
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jax==0.4.23
      - jax-jumpy==1.0.0
      - jaxlib==0.4.23
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.3.2
      - json-tricks==3.17.3
      - json5==0.9.14
      - jsonpickle==3.0.4
      - jsonpointer==2.4
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.5.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.12.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - keras==2.9.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - lab==8.0
      - labmaze==1.0.6
      - lazy-loader==0.3
      - libclang==16.0.6
      - llvmlite==0.41.1
      - lxml==4.9.3
      - lz4==4.3.2
      - mako==1.3.3
      - markdown==3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - minigrid==2.1.1
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - mmcv-full==1.7.1
      - mmpose==0.28.0
      - model-index==0.1.11
      - monotonic==1.6
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.7
      - mujoco==3.1.6
      - multidict==6.0.4
      - multiprocess==0.70.15
      - munch==4.0.0
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.12.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - ninja==1.11.1.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numba==0.58.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.15.0
      - onnxruntime==1.16.1
      - opencv-python==4.10.0.82
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.28
      - opt-einsum==3.3.0
      - optax==0.1.3
      - optuna==3.6.1
      - ordered-set==4.1.0
      - oss2==2.17.0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.2
      - pathtools==0.1.2
      - pettingzoo==1.24.3
      - pexpect==4.8.0
      - pickle5==0.0.11
      - pillow==9.3.0
      - pip==23.3.1
      - platformdirs==3.11.0
      - plotly==5.18.0
      - pluggy==1.3.0
      - plyfile==1.0.1
      - proglog==0.1.10
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.39
      - protobuf==3.19.6
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybullet==3.2.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pygame==2.1.3
      - pyglet==1.5.27
      - pygments==2.16.1
      - pynvim==0.4.3
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pyqt6==6.7.0
      - pyqt6-qt6==6.7.1
      - pyqt6-sip==13.6.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pytest==7.4.3
      - pytest-instafail==0.5.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qt5-applications==5.15.2.2.3
      - qt5-tools==5.15.2.1.3
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - ray==2.9.3
      - referencing==0.30.2
      - regex==2023.10.3
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rl-utils==1.0.0
      - robosuite==1.4.0
      - rpds-py==0.10.6
      - rsa==4.9
      - ruamel-yaml==0.18.3
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.3.7
      - sacred==0.8.5
      - safetensors==0.4.0
      - sb3-contrib==2.2.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scikit-spatial==7.0.0
      - scipy==1.11.3
      - seaborn==0.13.2
      - seals==0.2.1
      - send2trash==1.8.2
      - sentry-sdk==1.9.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - shimmy==1.3.0
      - simplejson==3.19.2
      - six==1.16.0
      - smmap==5.0.1
      - smplx==0.1.28
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - stable-baselines3==2.2.1
      - stack-data==0.6.3
      - structlog==23.2.0
      - submitit==1.5.0
      - supervision==0.16.0
      - swig==4.1.1
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensordict==0.2.1
      - tensordict-nightly==2023.12.10
      - tensorflow==2.9.0
      - tensorflow-estimator==2.9.0
      - tensorflow-io-gcs-filesystem==0.35.0
      - termcolor==2.3.0
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - timm==0.4.12
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.1.0+cu118
      - torchaudio==2.1.0+cu118
      - torchgeometry==0.1.2
      - torchrl-nightly==2023.6.20
      - torchsnapshot==0.1.0
      - torchvision==0.16.0+cu118
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - transformers==4.25.1
      - trimesh==4.0.1
      - triton==2.1.0
      - txt2tags==3.9
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.25.11
      - wandb==0.16.2
      - wasabi==1.1.2
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.16.0
      - xtcocotools==1.14.3
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.2
      - zipp==3.19.2
prefix: /home/aries/anaconda3/envs/belief
